-- 호행처럼 공시/실적 장기 보관용 최소 스키마
-- 원문 문서/HTML/PDF/XBRL 전체는 저장하지 않고, 검색·분석에 필요한 메타데이터와 핵심 Fact만 저장한다.

create table if not exists public.investment_disclosures (
  id bigint generated by default as identity primary key,
  source text not null check (source in ('SEC', 'DART')),
  source_id text not null,
  source_entity_id text,
  market text not null check (market in ('US', 'KR')),
  exchange text not null,
  ticker text,
  company text not null,
  category text not null,
  importance smallint not null default 0,
  title text not null,
  form text not null,
  filing_date date not null,
  source_url text not null,
  detail_url text,
  amendment boolean not null default false,
  structured_earnings boolean not null default false,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  unique (source, source_id)
);

create index if not exists investment_disclosures_filing_date_idx
  on public.investment_disclosures (filing_date desc);
create index if not exists investment_disclosures_ticker_idx
  on public.investment_disclosures (ticker, filing_date desc);
create index if not exists investment_disclosures_category_idx
  on public.investment_disclosures (category, filing_date desc);
create index if not exists investment_disclosures_market_idx
  on public.investment_disclosures (market, filing_date desc);

create table if not exists public.investment_disclosure_facts (
  id bigint generated by default as identity primary key,
  disclosure_id bigint not null references public.investment_disclosures(id) on delete cascade,
  fact_key text not null,
  label text not null,
  value numeric not null,
  unit text not null,
  period_start date,
  period_end date,
  concept text,
  source text not null default 'SEC_XBRL',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (disclosure_id, fact_key)
);

create index if not exists investment_disclosure_facts_disclosure_idx
  on public.investment_disclosure_facts (disclosure_id);

create table if not exists public.disclosure_collection_runs (
  id bigint generated by default as identity primary key,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  status text not null default 'running',
  source_date_us date,
  source_date_kr date,
  fetched_count integer not null default 0,
  archived_count integer not null default 0,
  skipped_count integer not null default 0,
  facts_saved integer not null default 0,
  error text
);

alter table public.investment_disclosures enable row level security;
alter table public.investment_disclosure_facts enable row level security;
alter table public.disclosure_collection_runs enable row level security;

comment on table public.investment_disclosures is
  'SEC/DART 중요 공시 메타데이터 아카이브. 원문은 저장하지 않고 source_url로 연결.';
comment on table public.investment_disclosure_facts is
  '공시에서 공식적으로 확인된 핵심 수치만 저장. 생성형 요약/추정치/컨센서스는 저장하지 않음.';
